Test multiple platforms

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -47,7 +47,7 @@ jobs:
     - run: pnpm install --shamefully-hoist
     - run: VICE_DIRECTORY="/Applications/${{ matrix.vice_directory }}/bin" pnpm build:test
     - continue-on-error: true
-      run: VICE_DIRECTORY="/Applications/${{ matrix.vice_directory }}/bin" USE_XVFB=1 pnpm testmerge
+      run: VICE_DIRECTORY="/Applications/${{ matrix.vice_directory }}/bin" USE_XVFB=1 pnpm test
 
     - name: Test Report
       uses: dorny/test-reporter@v1
@@ -106,12 +106,35 @@ jobs:
     - run: ln -s $PWD/system /usr/share/vice
     - run: ls -l /usr/local/share
 
-    - run: VICE_SVN_VERSION=${{ matrix.vice_version }} ${{ matrix.vice_directory }} USE_XVFB=1 pnpm testmerge
+    - run: rm *.testrun.xml && TEST_PROGRAM=$PWD/src/__tests__/simple-project/program.c64 VICE_SVN_VERSION=${{ matrix.vice_version }} ${{ matrix.vice_directory }} USE_XVFB=1 pnpm test
+      continue-on-error: true
 
     - name: Test Report
       uses: dorny/test-reporter@v1
       if: success() || failure()    # run this step even if previous step failed
       with:
-        name: "Test Results: Linux: VICE ${{ matrix.vice_version }}"
+        name: "Test Results: Linux: VICE ${{ matrix.vice_version }}: C64"
+        path: "*.testrun.xml"
+        reporter: jest-junit
+
+    - run: rm *.testrun.xml && TEST_PROGRAM=$PWD/src/__tests__/simple-project/program.pet VICE_SVN_VERSION=${{ matrix.vice_version }} ${{ matrix.vice_directory }} USE_XVFB=1 pnpm test
+      continue-on-error: true
+
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: "Test Results: Linux: VICE ${{ matrix.vice_version }}: PET"
+        path: "*.testrun.xml"
+        reporter: jest-junit
+
+    - run: rm *.testrun.xml && TEST_PROGRAM=$PWD/src/__tests__/simple-project/program.nes VICE_SVN_VERSION=${{ matrix.vice_version }} ${{ matrix.vice_directory }} USE_XVFB=1 pnpm test
+      continue-on-error: true
+
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: "Test Results: Linux: NES"
         path: "*.testrun.xml"
         reporter: jest-junit
